### ISSUE TITLE
Catch and report errors

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#18]
I just added some new PEPs to the pephub.github.org repo. I did it blind without testing. When I try to access those endpoints, I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 250, in app
    response = actual_response_class(response_data, **response_args)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 157, in render
    return json.dumps(
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

In addition the validating on pephub submission (a github action in pephub, see #15), we should also do some defensive programming here to catch these errors and return an informative message to the user, in case something sneaks by the validation script.

**Comment by nleroy917** [comment]
Looks like this isn't an issue with `peppy` and more an issue with us trying to return something that isn't JSON serializable... So it may be a valid PEP, but one that contains data that can't be returned via JSON?

**Comment by nsheff** [comment]
OK yes, we should solve that issue too.

But the current issue is to catch these *kind* of errors and return a meaningful message to the user.

**Comment by nsheff** [comment]
ideally we could catch this particular issue at the validation stage now that we know it.

**Comment by nsheff** [comment]
@nleroy917 I think this is something that needs to be fixed at this point.

**Comment by nsheff** [comment]
Here's another example:

```
OSError: Project config file path does not exist: ./peps/nfcore/demo_rna/samplesheet.yaml
INFO:     52.206.204.252:45478 - "GET /favicon.ico HTTP/1.0" 404 Not Found
INFO:     52.206.204.252:45484 - "GET /pep/nfcore/demo_rna HTTP/1.0" 307 Temporary Redirect
INFO:     52.206.204.252:45486 - "GET /pep/nfcore/demo_rna/ HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    solved_result = await solve_dependencies(
  File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 521, in solve_dependencies
    solved = await solve_generator(
  File "/usr/local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 442, in solve_generator
    return await stack.enter_async_context(cm)
  File "/usr/local/lib/python3.8/contextlib.py", line 568, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/local/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/lib/python3.8/site-packages/fastapi/concurrency.py", line 30, in contextmanager_in_threadpool
    raise e
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
OSError: Project config file path does not exist: ./peps/nfcore/demo_rna/samplesheet.yaml
```

You can see these errors with the data here:

- pephub.databio.org/pep/nfcore/demo_rna (this error)
- http://pephub.databio.org/pep/nfcore/demo_rna_pep/ (the above error)

**Comment by nleroy917** [comment]
So, I think this is because the specified `config_file` is not present inside that directory: https://github.com/pepkit/pephub.databio.org/tree/master/peps/nfcore/demo_rna

I don't see `samplesheet.yaml`

**Comment by nsheff** [comment]
> So, I think this is because the specified `config_file` is not present inside that directory: https://github.com/pepkit/pephub.databio.org/tree/master/peps/nfcore/demo_rna
> 
> I don't see `samplesheet.yaml`

That is correct.

**Comment by nleroy917** [comment]
So, we should notify the user that the config file is not found

**Comment by nsheff** [comment]
well, see above:

> ideally we could catch this particular issue at the validation stage now that we know it.

We need 2 layers. The validation layer, and then what do you tell the user if the data is bad anyway?  Some kind of message, but I don't know that it needs to be *that* specific. Or maybe you can just pass the python error back.

**Comment by nsheff** [comment]
what do you think? I think you can come up with a solution that makes sense to you. I don't think "Internal Server Error" is the best way.

**Comment by nleroy917** [comment]
I agree. I think we decided to leave validation at the instance level, but if that fails having a nice catch inside the server wouldn't hurt anything if it's just a few lines. We can add something to check this -- however, is there some sort of global error-catching feature you envision? I'm sure there will always be more errors than we can think of right now.. so is there a solution (in FastAPI) that will just pass back the 500? That seems to be the wrong approach, since then you're hiding internal server errors...

**Comment by nleroy917** [comment]
I think that this issue is no longer relevant with the move to a database representation of a PEP.
