### ISSUE TITLE
PEPhub down?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub#187]
1. Right now if I search on pephub, I get a blank page.
2. I can't show my PEPs either, I get an error.

**Comment by nleroy917** [comment]
![image](https://github.com/pepkit/pephub/assets/41063083/32410b9f-7483-40b6-95be-a4c3e88c4192)

Something is really broken - did we make a database change? Ton's of 500's. We haven't deployed a new version in 5 days.

**Comment by nleroy917** [comment]
@khoroshevskyi ???

**Comment by nleroy917** [comment]
Even with a fresh `venv` install, I can't replicate this locally - what are the server logs saying?

**Comment by khoroshevskyi** [comment]
> @khoroshevskyi ???

idk, we should look into logs 😬

**Comment by nleroy917** [comment]
Log out and log back in, and the issue is resolved. Must be a JWT issue. The move to `localStorage` got rid of all the auto-expiration logic on the client, so we must be doing something wrong on the backend when handling expired tokens.

**Comment by nsheff** [comment]
```
File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/pephub/routers/eido/eido.py", line 385, in validate
    schema_dict = eido.read_schema(schema_file.name)[0]
 File "/usr/local/lib/python3.10/site-packages/eido/schema.py", line 79, in read_schema
    raise TypeError(
TypeError: schema has to be a dict, path to an existing file or URL to a remote one. Got: <class 'str'>
```

**Comment by nsheff** [comment]
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/app/pephub/middleware.py", line 15, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    solved_result = await solve_dependencies(
  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 624, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/pephub/dependencies.py", line 165, in get_user_from_session_info
    user = session_info.get("login")
AttributeError: 'HTTPException' object has no attribute 'get'
[INFO] [Jun 26 2023 16:43:07] [PEPHUB] 52.206.204.252:35006 - "GET /api/v1/namespaces/nsheff/ HTTP/1.1" 500
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock




```

**Comment by nleroy917** [comment]
This is the block that is **supposed** to check for expired JWT's:
```python
def read_authorization_header(Authorization: str = Header(None)) -> Union[str, None]:
    """
    Reads and decodes a JWT, returning the decoded variables.

    @param session_info_encoded: JWT provided via FastAPI injection from the API cookie.
    """
    if Authorization is None:
        return None
    else:
        Authorization = Authorization.replace("Bearer ", "")
    try:
        # Python jwt.decode verifies content as well so this is safe.
        session_info = jwt.decode(Authorization, JWT_SECRET, algorithms=["HS256"])
    except jwt.exceptions.InvalidSignatureError as e:
        _LOGGER_PEPHUB.error(e)
        return None
    except jwt.exceptions.DecodeError as e:
        _LOGGER_PEPHUB.error(e)
        return None
    except jwt.exceptions.ExpiredSignatureError:
        return HTTPException(status_code=401, detail="JWT has expired")
    return session_info
```

Wonder if that `jwt.exceptions.ExpiredSignatureError` isn't catching and it's returning an empty `session_info`

**Comment by nleroy917** [comment]
I am able to reproduce this locally by setting the JWT expiration time to 5 seconds. I'll try to do two things: 1) not cause the server to crash when the token is expired, and 2) write logic on the frontend to request a new login once the token is expired.

**Comment by nleroy917** [comment]
I see the bug. One shouldn't `return HTTPException(status_code=401, detail="JWT has expired")`, it's an exception so we need to `raise HTTPException(status_code=401, detail="JWT has expired")`

**Comment by nsheff** [comment]
There are 2 instances where exceptions were returned rather than raised, probably need to fix both.

**Comment by nleroy917** [comment]
> There are 2 instances where exceptions were returned rather than raised, probably need to fix both.

Got it. Fixed the other one.
